import React from 'react';
import Image from 'next/image';
import Link from 'next/link';

function OurBlog() {
  return (
    <div>
          <div
              className='
                    pt-16
                    md:flex
                    md:ml-20
                    flex
                    justify-center
                    '
          >
              <Image
                  src="https://restho-nextjs.vercel.app/assets/images/icon/sub-title-vec.svg"
                  width={20}
                  height={20}
              />
              <p className='
                        text-amber-400
                        mx-3
                        md:text-lg
                        text-md
                    '
              >
                  Online Reserve
              </p>
              <Image
                  src="https://restho-nextjs.vercel.app/assets/images/icon/sub-title-vec.svg"
                  width={20}
                  height={20}
              />
          </div> 
          <div className='flex justify-center mt-7'>
            <h1 className='font-bold font-serif text-3xl md:text-5xl'>Our Latest Blog</h1>
          </div>
          <div className='md:flex justify-center mt-10'>
              <div className='flex justify-center md:mt-0 mt-10'>
          <div 
            className='
                relative
                rounded-lg
                bg-center
                bg-cover
                w-[300px]
                h-[250px]
                bg-[url("https://restho-nextjs.vercel.app/assets/images/bg/h2-blog1.png")]
            '>
                <Link
                    href="#"
                    className='
                        rounded-lg 
                        text-white 
                        absolute 
                        px-4 
                        py-2 
                        m-4 
                        top-0 
                        right-0 
                        bg-white 
                        hover:bg-amber-700
                        hover:text-white
                    '>
                    <h1 
                        className='
                            text-amber-700 
                            font-bold 
                            text-xl
                            hover:text-white
                        '
                    >
                            17
                    </h1>
                    <p 
                        className='
                            text-amber-700 
                            text-sm
                            hover:text-white
                        '
                    >
                        April
                    </p>
                </Link>
            </div>
            </div>
            <div className='flex justify-center md:mt-0 mt-10'>
            <div
            className='
                md:ml-10
                relative
                rounded-lg
                bg-center
                bg-cover
                w-[300px]
                h-[250px]
                bg-[url("https://restho-nextjs.vercel.app/assets/images/bg/h2-blog2.png")]
            '>
                  <Link
                      href="#"
                      className='
                        rounded-lg 
                        text-white 
                        absolute 
                        px-4 
                        py-2 
                        m-4 
                        top-0 
                        right-0 
                        bg-white 
                        hover:bg-amber-700
                        hover:text-white
                    '>
                      <h1
                          className='
                            text-amber-700 
                            font-bold 
                            text-xl
                            hover:text-white
                        '
                      >
                          18
                      </h1>
                      <p
                          className='
                            text-amber-700 
                            text-sm
                            hover:text-white
                        '
                      >
                          Apr
                      </p>
                  </Link>
              </div>
              </div>
              <div className='flex justify-center md:mt-0 mt-10'>
              <div
                className='
                md:ml-10
                relative
                rounded-lg
                bg-center
                bg-cover
                w-[300px]
                h-[250px]
                bg-[url("https://restho-nextjs.vercel.app/assets/images/bg/h2-blog3.png")]
            '>
                  <Link
                      href="#"
                      className='
                        rounded-lg 
                        text-white 
                        absolute 
                        px-4 
                        py-2 
                        m-4 
                        top-0 
                        right-0 
                        bg-white 
                        hover:bg-amber-700
                        hover:text-white
                    '>
                      <h1
                          className='
                            text-amber-700 
                            font-bold 
                            text-xl
                            hover:text-white
                        '
                      >
                          17
                      </h1>
                      <p
                          className='
                            text-amber-700 
                            text-sm
                            hover:text-white
                        '
                      >
                          Apr
                      </p>
                  </Link>
              </div>
              </div>
          </div>
    </div>
  )
}

export default OurBlog